/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BackendHealth { 'version' : string, 'timestamp' : bigint }
export interface Holding {
  'id' : bigint,
  'startTime' : Time,
  'endTime' : Time,
  'owner' : Principal,
  'positionStatus' : PositionStatus,
  'tokenAmount' : bigint,
  'lockDurationDays' : bigint,
}
export type PositionStatus = { 'expired' : null } |
  { 'locked' : null } |
  { 'unlocked' : null };
export interface Product { 'id' : string }
export interface Proposal {
  'id' : bigint,
  'status' : ProposalStatus,
  'title' : string,
  'creator' : Principal,
  'votes' : ProposalVotes,
  'description' : string,
}
export type ProposalStatus = { 'closed' : null } |
  { 'open' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ProposalVotes {
  'no' : bigint,
  'yes' : bigint,
  'abstain' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VoteOption = { 'no' : null } |
  { 'yes' : null } |
  { 'abstain' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkBackendHealth' : ActorMethod<[], BackendHealth>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createHolding' : ActorMethod<[bigint, bigint], bigint>,
  'createProposal' : ActorMethod<[string, string], bigint>,
  'deleteHolding' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getAllHoldings' : ActorMethod<[], Array<Holding>>,
  'getAllProposals' : ActorMethod<[], Array<Proposal>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHolding' : ActorMethod<[bigint], [] | [Holding]>,
  'getLaunchDate' : ActorMethod<[], string>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProposal' : ActorMethod<[bigint], [] | [Proposal]>,
  'getPublicationState' : ActorMethod<[], boolean>,
  'getReceiverPrincipal' : ActorMethod<[], Principal>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserHoldings' : ActorMethod<[Principal], Array<Holding>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'proxyIcpKlines' : ActorMethod<[], string>,
  'proxyIcpPrice' : ActorMethod<[], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setPublicationState' : ActorMethod<[boolean], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unlockHolding' : ActorMethod<[bigint], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
  'voteOnProposal' : ActorMethod<[bigint, VoteOption], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];