/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Product = IDL.Record({ 'id' : IDL.Text });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BackendHealth = IDL.Record({
  'version' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Time = IDL.Int;
export const PositionStatus = IDL.Variant({
  'expired' : IDL.Null,
  'locked' : IDL.Null,
  'unlocked' : IDL.Null,
});
export const Holding = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : Time,
  'endTime' : Time,
  'owner' : IDL.Principal,
  'positionStatus' : PositionStatus,
  'tokenAmount' : IDL.Nat,
  'lockDurationDays' : IDL.Nat,
});
export const ProposalStatus = IDL.Variant({
  'closed' : IDL.Null,
  'open' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const ProposalVotes = IDL.Record({
  'no' : IDL.Nat,
  'yes' : IDL.Nat,
  'abstain' : IDL.Nat,
});
export const Proposal = IDL.Record({
  'id' : IDL.Nat,
  'status' : ProposalStatus,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'votes' : ProposalVotes,
  'description' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const VoteOption = IDL.Variant({
  'no' : IDL.Null,
  'yes' : IDL.Null,
  'abstain' : IDL.Null,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addProduct' : IDL.Func([Product], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkBackendHealth' : IDL.Func([], [BackendHealth], ['query']),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createHolding' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
  'createProposal' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'deleteHolding' : IDL.Func([IDL.Nat], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'getAllHoldings' : IDL.Func([], [IDL.Vec(Holding)], ['query']),
  'getAllProposals' : IDL.Func([], [IDL.Vec(Proposal)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHolding' : IDL.Func([IDL.Nat], [IDL.Opt(Holding)], ['query']),
  'getLaunchDate' : IDL.Func([], [IDL.Text], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProposal' : IDL.Func([IDL.Nat], [IDL.Opt(Proposal)], ['query']),
  'getPublicationState' : IDL.Func([], [IDL.Bool], ['query']),
  'getReceiverPrincipal' : IDL.Func([], [IDL.Principal], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserHoldings' : IDL.Func([IDL.Principal], [IDL.Vec(Holding)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'proxyIcpKlines' : IDL.Func([], [IDL.Text], []),
  'proxyIcpPrice' : IDL.Func([], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setPublicationState' : IDL.Func([IDL.Bool], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unlockHolding' : IDL.Func([IDL.Nat], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
  'voteOnProposal' : IDL.Func([IDL.Nat, VoteOption], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Product = IDL.Record({ 'id' : IDL.Text });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BackendHealth = IDL.Record({
    'version' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Time = IDL.Int;
  const PositionStatus = IDL.Variant({
    'expired' : IDL.Null,
    'locked' : IDL.Null,
    'unlocked' : IDL.Null,
  });
  const Holding = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : Time,
    'endTime' : Time,
    'owner' : IDL.Principal,
    'positionStatus' : PositionStatus,
    'tokenAmount' : IDL.Nat,
    'lockDurationDays' : IDL.Nat,
  });
  const ProposalStatus = IDL.Variant({
    'closed' : IDL.Null,
    'open' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const ProposalVotes = IDL.Record({
    'no' : IDL.Nat,
    'yes' : IDL.Nat,
    'abstain' : IDL.Nat,
  });
  const Proposal = IDL.Record({
    'id' : IDL.Nat,
    'status' : ProposalStatus,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'votes' : ProposalVotes,
    'description' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const VoteOption = IDL.Variant({
    'no' : IDL.Null,
    'yes' : IDL.Null,
    'abstain' : IDL.Null,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addProduct' : IDL.Func([Product], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkBackendHealth' : IDL.Func([], [BackendHealth], ['query']),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createHolding' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
    'createProposal' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'deleteHolding' : IDL.Func([IDL.Nat], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'getAllHoldings' : IDL.Func([], [IDL.Vec(Holding)], ['query']),
    'getAllProposals' : IDL.Func([], [IDL.Vec(Proposal)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHolding' : IDL.Func([IDL.Nat], [IDL.Opt(Holding)], ['query']),
    'getLaunchDate' : IDL.Func([], [IDL.Text], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProposal' : IDL.Func([IDL.Nat], [IDL.Opt(Proposal)], ['query']),
    'getPublicationState' : IDL.Func([], [IDL.Bool], ['query']),
    'getReceiverPrincipal' : IDL.Func([], [IDL.Principal], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserHoldings' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Holding)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'proxyIcpKlines' : IDL.Func([], [IDL.Text], []),
    'proxyIcpPrice' : IDL.Func([], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setPublicationState' : IDL.Func([IDL.Bool], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unlockHolding' : IDL.Func([IDL.Nat], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
    'voteOnProposal' : IDL.Func([IDL.Nat, VoteOption], [], []),
  });
};

export const init = ({ IDL }) => { return []; };